In [12]:
import numpy as np 
arr_zeros = np.zeros(10)
print(arr_zeros)
arr_zeros

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr_zeros[5] = 1
print("Cập nhật phần tử ở vị trí thứ 5 là 1:",arr_zeros)

Cập nhật phần tử ở vị trí thứ 5 là 1: [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [21]:
arr_h = np.arange(10,25,1)
print(arr_h)
arr_nguoc = arr_h[::-1]
print("In danh sách các phần tử theo thứ tự đảo ngược của arr_h:",arr_nguoc)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
In danh sách các phần tử theo thứ tự đảo ngược của arr_h: [24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [23]:
arr_k = np.array([1,2,0,8,2,0,1,3,0,5,0])
arr_1 = arr_k[arr_k != 0] 
print("Tạo arr_1 với các phần tử khác 0 từ arr_k:",arr_1)

Tạo arr_1 với các phần tử khác 0 từ arr_k: [1 2 8 2 1 3 5]


In [48]:
arr_1
arr_1_new = np.append(arr_1,[10,20])
print("Thêm phần tử có giá trị 10 và 20 ở cuối array:",arr_1_new)

Thêm phần tử có giá trị 10 và 20 ở cuối array: [ 1  2  8  2  1  3  5 10 20]


In [49]:
arr_1_new 
arr_1_new = np.insert(arr_1_new,5,100)
print("Thêm phần tử có giá trị = 100 vào vị trí có index=5: ",arr_1_new)

Thêm phần tử có giá trị = 100 vào vị trí có index=5:  [  1   2   8   2   1 100   3   5  10  20]


In [53]:
arr_1_new
arr_delete= np.delete(arr_1_new,[0,1,2])
print("Xóa các phần tử tại vị trí có index = 0,1,2:",arr_delete)

Xóa các phần tử tại vị trí có index = 0,1,2: [  2   1 100   3   5  10  20]
