In [ ]:
import numpy as np 
arr = np.arange(1,10) #  tạo mảng từ 1->9
print(f'Mảng 1 chiều ban đầu: \n',arr)
grid = arr.reshape((3,3)) # tạo thành bảng 3x3
print(f'Mảng 2 chiều sau khi reshape:\n',grid)

Mảng 1 chiều ban đầu: 
 [1 2 3 4 5 6 7 8 9]
Mảng 2 chiều sau khi reshape:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
