In [5]:
import numpy as np
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
arr_view = arr_2d[:2, :2].view() # tạo view mới từ slicing chỉ chứa 2 dòng avf 2 cột của mảng gốc
print(arr_view)
## thay đổi giá trị trong view 
arr_view[ 0,0] = 100 # chỉnh sửa phần tử ở dòng 0, cột 0 thành 10 
print(arr_view)
print(arr_2d)
type(arr_view)

[[1 2]
 [4 5]]
[[100   2]
 [  4   5]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


numpy.ndarray