In [1]:
import numpy as np 
import pandas as pd 
np.random.seed(0)
arr = np.random.randint(10,size=(3,4))
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [2]:
# BROAdcasting trong numpy
arr[0]

array([5, 0, 3, 3], dtype=int32)

In [3]:
arr - arr[0]

array([[ 0,  0,  0,  0],
       [ 2,  9,  0,  2],
       [-3,  4,  4,  3]], dtype=int32)

In [7]:
# vd trong pandas 
df = pd.DataFrame(arr,columns=['P','Q','M','N'])
print("df:\n",df)


df:
    P  Q  M  N
0  5  0  3  3
1  7  9  3  5
2  2  4  7  6


In [8]:
df.iloc[0]

P    5
Q    0
M    3
N    3
Name: 0, dtype: int32

In [9]:
df.iloc[0].index

Index(['P', 'Q', 'M', 'N'], dtype='object')